### ISSUE TITLE
Provide Unity Events for all C# Delegates

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK.Unity.Core#12]
By default all events in VRTK will be C# delegates, but a Unity Events helper will be provided to allow for Unity Events for any C# delegate.

**Comment by thestonefox** [comment]
Probably can close this as we don't need it if we're only ever using UnityEvents

**Comment by bddckr** [comment]
Agreed. We decided on going with `UnityEvent`s only for the following reasons:

1. Unity uses it, so it's known and expected in the Unity community.
2. They support wiring things up in the inspector without us doing anything fancy to serialize those event subscriptions ourselves.
3. Any helper needs to generate UnityEvent subclasses. We're talking about code generation for the user. This means we force you to wait for a recompile and additionally make it harder to change and delete types since the generated classes give you compile errors and need to be updated.
4. C# events have better performance but we're really using events as events. Rather than emitting state all the time we fire only on state **changes**. Worst case is something like an axis event on a controller, but even then that's fine and negligible in comparison of what any Unity title typically does as a whole in any given frame.

Closing now. Can open up again in case we decide there's a need for this.
