### ISSUE TITLE
Suggestion: Remove "Facade" from class names

### ISSUE THREAD

**Issue by andybak** [ExtendRealityLtd/VRTK.Unity.Core#183]
I just took my first peek at VRTK 4 and the I came across "InteractorVisibilityModifierFacade".

I couldn't help be reminded of the notorious AbstractSingletonProxyFactoryBean ;-)

Would anything really suffer if was renamed InteractorVisibilityModifier ( or even "InteractorVisibilityMod") ? I suspect clarity and code aesthetics would improve if the "Facade" suffix was dropped throughout the framework with very little downside that I can see.

I am trying to imagine teaching use of VRTK to non-professional developers and I'm wincing at the thought of introducing these class names.

It might seem like a minor thing but naming matters and good APIs have good naming conventions. I'm a Python dev originally and this feels a bit too "enterprisey" for comfort

**Comment by thestonefox** [comment]
a `InteractorVisibilityModifier` is a class that would modify the interactor visibility

a facade class is not doing anything other than being a facade to underlying systems

that's why `InteractorVisibilityModifierFacade` is the correct name, because that class is purely a facade to the underlying systems.

**Comment by andybak** [comment]
I wasn't disputing it's correctness.

**Comment by bddckr** [comment]
The facades work together with the prefab they come with. To prevent confusion between the
* prefab
* actual component this is a facade to
* and the facade itself

we need a specific name. I'm not bound to "facade" but I don't see a better solution either. This shouldn't feel enterprise-y, it should feel like proper CS terms are used that can therefore be looked up easily in case a user never heard about the term before.

**Comment by andybak** [comment]
>  it should feel like proper CS terms

However, a large chunk of the (presumed) intended audience for VRTK aren't computer scientists. :) Unity supports a broad range of usage patterns and programming experience and the real hardcore devs are probably off rolling their own frameworks.

I'd have no real issue with the naming if it was only ever visible in the source - but because it's used in the inspector UI different standards should apply. It's part of your UI. You hopefully wouldn't give a UI control a label with 30 odd characters in it.

I guess my point is simply that any names visible in the Editor UI should be short, clear and natural-sounding.

(It's not just "noobs don't know what facades are!" either) Even to someone like me - it sends a bit of a negative signal about how approachable and cleanly designed the framework is going to be. A bit like buying a gadget and seeing the wires are sticking out of the box...)

**Comment by bddckr** [comment]
I agree to a certain degree.

I am more than happy to discuss alternatives and I can't come up with any. The solution can't be dropping the "facade" suffix because my above explanation of the same prefix being used elsewhere.

If a user gets confused by a suffix I don't think we can help them, even with the planned detailed documentation.

**Comment by andybak** [comment]
> If a user gets confused by a suffix

I'd dispute the term "confused" as it makes it sound like the user is at fault. Developers are often drawn towards elegance and simplicity in their choice of tools. I wouldn't characterize an aversion to verbosity as a flaw...

I haven't dug in deeply enough to be much help in suggesting alternatives but I'm pleased to see the new VRTK release has made so much progress. I've been stuck in native GoogleVR land for the last few months...

**Comment by bddckr** [comment]
I think we're fine for now because the documentation and any instruction to the user will be:
1. Drag n drop the prefab named X into the scene
1. In the inspector set the following settings up

The latter is fine - there is only one component visible to the user on prefabs - the facade.

Once a user wants to drill down to any code they will *need* the term "facade" to understand it. There is no way around it and using proper terminology here will ensure the user doesn't get confused.

---

Closing the issue as we want to keep the repo clean, but discussions can continue on here.
